### ISSUE TITLE
question for dependency of Ghpr.Console

### ISSUE THREAD

**Issue by davesliu** [GHPReporter/Ghpr.Console#37]
Hello,

I downloaded the Ghpr.Console from the VS nuget for my project and it's in the package of project.
I had already TestReport.xml that generated by nunit3-console.exe. I just want to use the Ghpr.Console.exe to convert the TestReport.xml files to html. 

I use the command in the packages\Ghpr.Console.0.9.9\lib\net452 folder:
=============================
$ ./Ghpr.Console.exe  TestReport.xml

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Ghpr.NUnit, Version=0.9.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Ghpr.Cli.ReportHelper.GenerateReport(String path)
   at Ghpr.Cli.Program.Main(String[] args)
==========================

The execution will be failed....

So is there any dependency of Ghpr.Console.exe ? or is there anything that missed?

**Comment by elv1s42** [comment]
Hi @davesliu !

Yes, there are extra dependencies required fro Console app to work correctly. For now there is one console application for both NUnit and MSTest test results, so it depends on both frameworks, but there is a plan to remove this dependencies in the future. The total list of dependencies is available here: https://github.com/GHPReporter/Ghpr.Console/blob/master/Ghpr.Console/packages.config

In general you should call the Ghpr.Console.exe from the build folder where you have all the referenced packages.

Thank you

**Comment by davesliu** [comment]
@elv1s42  
Thanks for your help. It works when we copied all dependency dll files to the same folder of exe file.

**Comment by elv1s42** [comment]
I've updated `README` to explicitly mention that dependencies should be in the same folder as `Ghpr.Console.exe` file.
