### ISSUE TITLE
Ghpr.Console produces empty report

### ISSUE THREAD

**Issue by UyttenhoveSimon** [GHPReporter/Ghpr.Console#43]
Hello,

**Bug:**
While trying Ghpr.Console on Ghpr.Examples, it produced an empty report.
![image](https://user-images.githubusercontent.com/3716879/64264000-e80c2280-cf30-11e9-81eb-bacced462fd6.png)

**How to reproduce:**
1) Installed all the latest required packages from GHPR (Core (0.9.9.1), Nunit (0.9.9.1), NUnitTests (1.0.0.0), Console (0.9.9.1)).
2) Installed inside the addin of NUnit Console: addins/../../../Users/suyttenhove/Documents/TestGHPR/Ghpr.NUnit.Examples/bin/x86/Debug/Ghpr.NUnit.dll
3) I started from Ghpr.NunitExamples.
4) Did the tests and produced the .xml with NUnit Console within Ghpr.NUnit.Examples\Ghpr.NUnitExamples\bin\x86\Debug\\ .

NUnit.Settings.json looks like this:
`
{
  "default": {
    "outputPath": "C:\\",
    "dataServiceFile": "Ghpr.LocalFileSystem.dll",
    "loggerFile": "",
    "sprint": "",
    "reportName": "GHP Report",
    "projectName": "Examples Projet",
    "runName": "",
    "runGuid": "",
    "realTimeGeneration": "True",
    "runsToDisplay": "5",
    "testsToDisplay": "5",
    "retention": {
      "amount": 1000,
      "till": "2020-01-25 10:00:00"
    }
  },
  "projects": [
    {
      "pattern": "Ghpr.NUnitExamples.dll",
      "settings": {
        "outputPath": "C:\\Users\\suyttenhove\\Documents\\TestGHPR\\Ghpr.NUnit.Examples\\bin\\x86\\Debug\\"
      }
    }
  ]
}
`

Would you have an idea as to why no Runs are reported?

When I use Extent Reports to produce the report, I get the correct result:
![image](https://user-images.githubusercontent.com/3716879/64264068-ff4b1000-cf30-11e9-99b8-fb8a2ecbecad.png)

Thanks,
Simon

**Comment by elv1s42** [comment]
Hi @UyttenhoveSimon !

Sorry for the late response.

Can you please check if you are following the `view report locally section` ? 
https://github.com/GHPReporter/Ghpr.Core#view-report-locally

Thank you

**Comment by elv1s42** [comment]
Hi @UyttenhoveSimon ,

The `index.html` file is empty and that's correct. The data for this file should be picked up by `.js` library, so you need to enable javascript for local files.
You can check the details for [firefox](https://github.com/GHPReporter/Ghpr.Core#firefox) and [chrome](https://github.com/GHPReporter/Ghpr.Core#chrome). Also you can check the Console of your browser to make sure there are no errors.

Thank you.

**Comment by UyttenhoveSimon** [comment]
Good news, it is working now. 
Closing the browser and opening it again with the flags worked.
Maybe mention this behavior in the doc?

Thanks for your responses.

**Comment by elv1s42** [comment]
@UyttenhoveSimon thank you for the feedback, I've updated corresponding section in the `README` file.
