### ISSUE TITLE
How to add screenshot to Ghpr.Console? It is possible?

### ISSUE THREAD

**Issue by jakismichal** [GHPReporter/Ghpr.Console#6]
Hey Guys, 
I'm very happy that you added Ghpr.Console it's cool. Do you have any idea how I can add screenshots to my report? Is it possible?

Cheers,
Michal

**Comment by elv1s42** [comment]
Hi @jakismichal !

The answer to your question depends on what framework you are using (MSTest or NUnit).
For NUnit if you run your tests with NUnit Console you need to use Ghpr.NUnit package to save screenshots. Then you can run Ghpr.Console and generate the report from `.xml` results file, but you need to make sure that both paths in Ghpr.NUnit and Ghpr.Console `.json` config files are the same.

Thank you

**Comment by jakismichal** [comment]
Awesome. Thank you!
