### ISSUE TITLE
Can't get a report generated

### ISSUE THREAD

**Issue by Tychus** [GHPReporter/Ghpr.Console#68]
I'm trying to use this in combination with `Nunit` and `dotnet test ...` the XML report generated is valid, all the dependencies are in there, the executable runs without giving any errors. I get the following 

```
Ghpr.Console.exe Common.Tests/test-result.xml
Generating the report for the file 'Common.Tests/test-result.xml'...
Generating the report done.
```

The report is nowhere to be found. I've also tried the Nunit version of GHPReported can't get any of them  to work.

**Comment by elv1s42** [comment]
Hi @Tychus!
Thank you for the issue. 
Can you please verify that you are using the latest versions of all `Ghpr.*` packages?
Also, if possible, you can send me your `.xml` report (in case it does not have any sensitive information)? so I can try to reproduce the issue locally. If you have any sensitive information in the report you can create a dummy NUnit test with some unique category and only this test by its category, so the report won't contain anything sensitive.

Also, you can check if your `.json` settings are correct. You can find more info here:
https://github.com/GHPReporter/Ghpr.Core#about-settings-file

Thank you
