### ISSUE TITLE
FileNotFoundException:  Could not load file or assembly 'Ghpr.NUnit, 

### ISSUE THREAD

**Issue by bcexopolllo** [GHPReporter/Ghpr.Console#7]
C:\Work\Sources\Automation\packages\Ghpr.Console.0.8.1\lib>Ghpr.Console.exe C:\Work\Sources\Automation\TestResult.xml

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Ghpr.NUnit, Version=0.8.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Ghpr.Console.ReportHelper.GenerateReport(String path)
   at Ghpr.Console.Program.Main(String[] paths)

**Comment by elv1s42** [comment]
Hi @bcexopolllo !
Can you please make sure that you have Ghpr.NUnit installed in the same folder as Chpr.Console?

Thank you
